### PR TITLE
MonsterDebuggerConnector fix to output all the rest args

### PR DESCRIPTION
**Pull request by fljot**
see issue6 https://github.com/base42/LogMeister/issues/6

### CODE REVIEW

**Comment by jankeesvw** [comment]
what if you want all the arguments on one line?

**Comment by fljot** [comment]
Good point actually. Then it should be MonsterDebugger.trace(getSender(), args, ...) but this would lead to tracing array in MonsterDebugger, which means you have to expand it first to inspect deeper. That's how MonsterDebugger.log(...args) works (added by my request). So maybe you'll just change args[0] to args everywhere so I won't make new requests?

**Comment by fljot** [comment]
Decided anything?

**Comment by jankeesvw** [comment]
No, I still have to merge this, but there for I have to find some time to test if the pull request really works when you compile... Try to squeeze it in today :) Thanks for the reminder!

**Comment by fljot** [comment]
No, don't pull this. Just change "args[0]" to "args" everywhere in MonsterDebuggerConnector.

**Pull request closed without merging**
